apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom-4ofa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/partner-catalog-custom/partner-catalog-custom-4ofa@sha256:9a3468af83a5032132275dda69e582bd00b05fc9aaffa062b0e09c0f38fee493
        name: my-java-springboot
        resources: {}
status: {}
