apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom-4ofa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/partner-catalog-custom/partner-catalog-custom-4ofa@sha256:2a4c2929d9b680255192b1cd37aa95c57c6629178c603f92c5bf62c64a74542f
        name: my-java-springboot
        resources: {}
status: {}
