apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-custom-4ofa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/fduthill-tenant/partner-catalog-custom/partner-catalog-custom-4ofa@sha256:0bd1897345adc1b1e8e36e3e1163fd2e99a279d7e46f3528b552b4bd60841370
        name: my-java-springboot
        resources: {}
status: {}
